version: '3'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    restart: always
    environment: 
      WORDPRESS_DB_HOST: "ip-database" # <- change this
      WORDPRESS_DB_USER: "user"  # <- change this
      WORDPRESS_DB_PASSWORD: "database-password"  # <- change this
      WORDPRESS_DB_NAME: "database-name"  # <- change this
    volumes:
      - /home/ubuntu/wordpress:/var/www/html